### ISSUE TITLE
ACF Custom Fields disappear from Admin menu

### ISSUE THREAD

**Issue by ucnrs** [billerickson/EA-Genesis-Child#95]
I am using your Genesis Child them. I like to a lost because it is very fast. When I active your the child theme ACF Custom Fields disappear from Admin menu. I only see site options. Do you have any idea? Thank you for your help. Lobsang
<img width="1280" alt="Screen Shot 2020-01-31 at 9 34 21 AM" src="https://user-images.githubusercontent.com/9424166/73560965-e6c22180-440c-11ea-8dad-b7385c364ca4.png">
Here is the screen shot.

**Comment by billerickson** [comment]
Yes, that is by design so clients cannot modify the metaboxes. 

In your local development environment, add `define( 'WP_LOCAL_DEV', true );` to wp-config.php so you can access Custom Fields.

Alternatively, you can remove this feature by [removing these lines of code](https://github.com/billerickson/EA-Genesis-Child/blob/64c104897472cd0f0b7cd2e9f119757b1015d278/inc/acf.php#L15-L17) in acf.php.

**Comment by richardbuff** [comment]
I personally like to change the conditional Bill mentioned to instead check for my username instead of the constant, so that I can still see them in a non-local environment (but only change them locally).  Also, you can just directly go to the URL https://www.yourdomain.com/wp-admin/edit.php?post_type=acf-field-group at any time to see the fields.  All the filter is doing is removing the admin menu item, it's not actually disabling the interface.
